name: Continuous integration code quality checks

on:
  pull_request:
    branches: [trunk]
  push:
    branches: [trunk,add/linting-github-actions]

jobs:
  lint:
    name: Parallel lint
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v2

      # Setup PHP versions, run checks
      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Get composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install composer packages
        run: composer install --no-progress

      - name: Check for PHP errors
        run: composer lint

  phpcs_check:
    name: PHPCS check
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v2

      # Setup PHP versions, run checks
      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Get composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install composer packages
        run: composer install --no-progress

      - name: Check coding standards using PHPCS
        run: composer standards:check -- --runtime-set ignore_warnings_on_exit true --runtime-set testVersion 5.8-
