name: Deploy to Test Site

on:
  # Triggers the workflow only for the trunk branch
  push:
    branches: [ trunk ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Deploy-Theme
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: sftp://sftp.pressable.com:22/htdocs/wp-content/themes/twentytwentytwo/
          ftp-username: ${{ secrets.STAGING_USER }}
          ftp-password: ${{ secrets.STAGING_PASSWORD }}
          git-ftp-args: --insecure
          local-dir: ./
