name: Code Quality - Stylelint

on:
  pull_request:
    branches: [trunk]
  push:
    branches: [trunk,add/linting-github-actions]

jobs:
  stylelint:
    name: stylelint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm install
      run: npm install
    - name: stylelint
      uses: actions-hub/stylelint@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PATTERN: "**/*.css"