name: Code Quality - CSS

on:
  pull_request:
    branches: [trunk]
  push:
    branches: [trunk]

jobs:
  stylelint:
    name: stylelint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout
    - name: install node v14
      uses: actions/setup-node
      with:
        node-version: 14
    - name: npm install
      run: npm install
    - name: stylelint
      uses: actions-hub/stylelint@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PATTERN: "style.css"
